name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, darwin ]
        arch: [ amd64, arm64 ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Go Build
        run: CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -a -installsuffix cgo -o sigscan .
      - uses: actions/upload-artifact@v3
        with:
          name: sigscan-${{ matrix.os }}-${{ matrix.arch }}
          path: sigscan

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Documentation Build
        run: go run ./hack/generate-manual
      - uses: actions/upload-artifact@v3
        with:
          name: man-pages
          path: man/

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Rename Artifacts
        run: |
          mkdir bin
          mv sigscan-darwin-amd64/sigscan bin/sigscan-darwin-amd64 
          mv sigscan-darwin-arm64/sigscan bin/sigscan-darwin-arm64 
          mv sigscan-linux-amd64/sigscan bin/sigscan-linux-amd64 
          mv sigscan-linux-arm64/sigscan bin/sigscan-linux-arm64
          mkdir man
          mv man-pages/* man/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          body_path: CHANGELOG.md
          files: |
            LICENSE.txt
            bin/sigscan-*
            man/*